### ISSUE TITLE
Add Planet STAC schema when it is updated for SS01 / SS02 platforms.

### ISSUE THREAD

**Issue by cholmes** [planetlabs/open-stac#5]
The planet stac beta.2 schema didn't allow ss01 and ss02. I'm putting in the PR that changes those so we have iterative improvement, but once the schema is out with https://github.com/planetlabs/stac-extension/issues/19 fixed we should change them back - the platform should align with the string in the id.

_Originally posted by @cholmes in https://github.com/planetlabs/open-stac/pull/3#discussion_r1231281230_

**Comment by m-mohr** [comment]
I updated them to SS01/02 in #4, but removed the Planet extension from stac_extensions. PR #6 adds them again and updates to the new extension version once released

**Comment by cholmes** [comment]
Ok, cool. I changed the title. Will see if I can merge and do the release.

**Comment by m-mohr** [comment]
Do the release first, otherwise the merge will likely be blocked because the CI is failing :-)

**Comment by cholmes** [comment]
Oh yeah, I meant merge  the planet stac-extension one - https://github.com/planetlabs/stac-extension/pull/20#pullrequestreview-1482116974 and then do the schema release. Looks like I can't merge, am not authorized. Hopefully @tschaub can help.
