### ISSUE TITLE
move thumbnails from github to gcp

### ISSUE THREAD

**Issue by cholmes** [planetlabs/open-stac#6]
https://github.com/planetlabs/open-stac/pull/4 added a number of nice thumbnails. We should move them to google cloud to be consistent.

**Comment by cholmes** [comment]
Hey @m-mohr  - it looks like the thumbnails broke on our deployment, see https://radiantearth.github.io/stac-browser/#/external/www.planet.com/data/stac/open-skysat-data/angkor-wat/catalog.json

Can you change them to absolute so things work for now? I'll try to update soon.

**Comment by m-mohr** [comment]
It looks at the right location, but I assume the png file was not copied over? At least I wouldn't know the absolute URL to use here (except linking to GitHub). Maybe it's time to copy them to the Google bucket? :-) @cholmes

**Comment by cholmes** [comment]
Yeah, I was saying just link to the github images in the meantime - I had thought that's what you were going to do. I'll try to do it. Do you have any easy list of all of them?

**Comment by m-mohr** [comment]
Oh, I just added 4 thumbnails in total. It's a thumbnail.png in each of the following folders located in stac/open-skysat-data:
- angkor-war
- cocabamba-peru
- san-francisco
- sp-crater

**Comment by cholmes** [comment]
Ah, cool. Thanks!

**Comment by cholmes** [comment]
Ok, moved them over: https://storage.googleapis.com/open-cogs/planet-stac/sp-crater/thumbnail.png

If you can update the links to them that'd be awesome.

**Comment by m-mohr** [comment]
Done: https://github.com/planetlabs/open-stac/pull/12

**Comment by m-mohr** [comment]
@cholmes This can be closed, I think.
